Repository googleapis/java-recommendations-ai, pull requests merged in 2020-09, with the labels that each got.

#125 build(java): switch to release-publish app for notifying GitHub of release status
  .kokoro/release/stage.cfg
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: recommendationengine, automerge, cla: yes, context: full

#131 build(ci): enable auto-release for dependency-update-only releases
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: recommendationengine, cla: yes, context: full

#133 chore: regenerate README
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#145 chore: regenerate README
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#147 build(java): use yoshi-approver token for auto-approve
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#148 chore: add repo settings configuration
  .github/sync-repo-settings.yaml
Labels: api: recommendationengine, automerge, cla: yes

#153 chore(ci): skip autorelease workflow on non-release PRs
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: recommendationengine, automerge, cla: yes, context: full

#154 chore(ci): verify autorelease release PR content has changes
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#156 chore(java): use separate autosynth job for README
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#158 build: rename samples lint workflow to checkstyle to disambiguate branch protection with unit lint
  .github/workflows/samples.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
