Repository googleapis/java-recommendations-ai, pull requests merged in 2020-06, with the labels that each got.

#68 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#73 chore(java_templates): add default CODEOWNERS files for samples reviews
  .github/CODEOWNERS
  synth.metadata
Labels: automerge, cla: yes, context: full

#76 chore: turn on renovate-bot master issue for java repos
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#71 fix: remove duplicate classes provided by api-common
  proto-google-cloud-recommendations-ai-v1beta1/clirr-ignored-differences.xml
  proto-google-cloud-recommendations-ai-v1beta1/src/main/java/com/google/api/HttpBody.java
  proto-google-cloud-recommendations-ai-v1beta1/src/main/java/com/google/api/HttpBodyOrBuilder.java
  proto-google-cloud-recommendations-ai-v1beta1/src/main/java/com/google/api/HttpBodyProto.java
Labels: cla: yes

#79 chore: regenerate with updated protoc
  proto-google-cloud-recommendations-ai-v1beta1/src/main/java/com/google/cloud/recommendationengine/v1beta1/CatalogInlineSource.java
  proto-google-cloud-recommendations-ai-v1beta1/src/main/java/com/google/cloud/recommendationengine/v1beta1/CatalogItem.java
  proto-google-cloud-recommendations-ai-v1beta1/src/main/java/com/google/cloud/recommendationengine/v1beta1/CollectUserEventRequest.java
  proto-google-cloud-recommendations-ai-v1beta1/src/main/java/com/google/cloud/recommendationengine/v1beta1/CreateCatalogItemRequest.java
  proto-google-cloud-recommendations-ai-v1beta1/src/main/java/com/google/cloud/recommendationengine/v1beta1/CreatePredictionApiKeyRegistrationRequest.java
  proto-google-cloud-recommendations-ai-v1beta1/src/main/java/com/google/cloud/recommendationengine/v1beta1/DeleteCatalogItemRequest.java
  proto-google-cloud-recommendations-ai-v1beta1/src/main/java/com/google/cloud/recommendationengine/v1beta1/DeletePredictionApiKeyRegistrationRequest.java
  proto-google-cloud-recommendations-ai-v1beta1/src/main/java/com/google/cloud/recommendationengine/v1beta1/EventDetail.java
  proto-google-cloud-recommendations-ai-v1beta1/src/main/java/com/google/cloud/recommendationengine/v1beta1/FeatureMap.java
  proto-google-cloud-recommendations-ai-v1beta1/src/main/java/com/google/cloud/recommendationengine/v1beta1/GetCatalogItemRequest.java
  proto-google-cloud-recommendations-ai-v1beta1/src/main/java/com/google/cloud/recommendationengine/v1beta1/Image.java
  proto-google-cloud-recommendations-ai-v1beta1/src/main/java/com/google/cloud/recommendationengine/v1beta1/ImportCatalogItemsRequest.java
  proto-google-cloud-recommendations-ai-v1beta1/src/main/java/com/google/cloud/recommendationengine/v1beta1/ImportCatalogItemsResponse.java
  proto-google-cloud-recommendations-ai-v1beta1/src/main/java/com/google/cloud/recommendationengine/v1beta1/ImportErrorsConfig.java
  proto-google-cloud-recommendations-ai-v1beta1/src/main/java/com/google/cloud/recommendationengine/v1beta1/ImportMetadata.java
  proto-google-cloud-recommendations-ai-v1beta1/src/main/java/com/google/cloud/recommendationengine/v1beta1/ImportUserEventsRequest.java
  proto-google-cloud-recommendations-ai-v1beta1/src/main/java/com/google/cloud/recommendationengine/v1beta1/ImportUserEventsResponse.java
  proto-google-cloud-recommendations-ai-v1beta1/src/main/java/com/google/cloud/recommendationengine/v1beta1/InputConfig.java
  proto-google-cloud-recommendations-ai-v1beta1/src/main/java/com/google/cloud/recommendationengine/v1beta1/ListCatalogItemsRequest.java
  proto-google-cloud-recommendations-ai-v1beta1/src/main/java/com/google/cloud/recommendationengine/v1beta1/ListCatalogItemsResponse.java
  proto-google-cloud-recommendations-ai-v1beta1/src/main/java/com/google/cloud/recommendationengine/v1beta1/ListPredictionApiKeyRegistrationsRequest.java
  proto-google-cloud-recommendations-ai-v1beta1/src/main/java/com/google/cloud/recommendationengine/v1beta1/ListPredictionApiKeyRegistrationsResponse.java
  proto-google-cloud-recommendations-ai-v1beta1/src/main/java/com/google/cloud/recommendationengine/v1beta1/ListUserEventsRequest.java
  proto-google-cloud-recommendations-ai-v1beta1/src/main/java/com/google/cloud/recommendationengine/v1beta1/ListUserEventsResponse.java
  proto-google-cloud-recommendations-ai-v1beta1/src/main/java/com/google/cloud/recommendationengine/v1beta1/PredictRequest.java
  proto-google-cloud-recommendations-ai-v1beta1/src/main/java/com/google/cloud/recommendationengine/v1beta1/PredictResponse.java
  proto-google-cloud-recommendations-ai-v1beta1/src/main/java/com/google/cloud/recommendationengine/v1beta1/PredictionApiKeyRegistration.java
  proto-google-cloud-recommendations-ai-v1beta1/src/main/java/com/google/cloud/recommendationengine/v1beta1/ProductCatalogItem.java
  proto-google-cloud-recommendations-ai-v1beta1/src/main/java/com/google/cloud/recommendationengine/v1beta1/ProductDetail.java
  proto-google-cloud-recommendations-ai-v1beta1/src/main/java/com/google/cloud/recommendationengine/v1beta1/ProductEventDetail.java
  proto-google-cloud-recommendations-ai-v1beta1/src/main/java/com/google/cloud/recommendationengine/v1beta1/PurchaseTransaction.java
  proto-google-cloud-recommendations-ai-v1beta1/src/main/java/com/google/cloud/recommendationengine/v1beta1/PurgeUserEventsMetadata.java
  proto-google-cloud-recommendations-ai-v1beta1/src/main/java/com/google/cloud/recommendationengine/v1beta1/PurgeUserEventsRequest.java
  proto-google-cloud-recommendations-ai-v1beta1/src/main/java/com/google/cloud/recommendationengine/v1beta1/PurgeUserEventsResponse.java
  proto-google-cloud-recommendations-ai-v1beta1/src/main/java/com/google/cloud/recommendationengine/v1beta1/UpdateCatalogItemRequest.java
  proto-google-cloud-recommendations-ai-v1beta1/src/main/java/com/google/cloud/recommendationengine/v1beta1/UserEvent.java
  proto-google-cloud-recommendations-ai-v1beta1/src/main/java/com/google/cloud/recommendationengine/v1beta1/UserEventImportSummary.java
  proto-google-cloud-recommendations-ai-v1beta1/src/main/java/com/google/cloud/recommendationengine/v1beta1/UserEventInlineSource.java
  proto-google-cloud-recommendations-ai-v1beta1/src/main/java/com/google/cloud/recommendationengine/v1beta1/UserInfo.java
  proto-google-cloud-recommendations-ai-v1beta1/src/main/java/com/google/cloud/recommendationengine/v1beta1/WriteUserEventRequest.java
  synth.metadata
Labels: automerge, cla: yes, context: partial

#81 build(java): skip lint on samples directory
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#86 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#90 fix: migrate recommendationengine/v1beta1 to grpc_service_config
  google-cloud-recommendations-ai/src/main/java/com/google/cloud/recommendationengine/v1beta1/CatalogServiceClient.java
  google-cloud-recommendations-ai/src/main/java/com/google/cloud/recommendationengine/v1beta1/CatalogServiceSettings.java
  google-cloud-recommendations-ai/src/main/java/com/google/cloud/recommendationengine/v1beta1/PredictionApiKeyRegistryClient.java
  google-cloud-recommendations-ai/src/main/java/com/google/cloud/recommendationengine/v1beta1/PredictionApiKeyRegistrySettings.java
  google-cloud-recommendations-ai/src/main/java/com/google/cloud/recommendationengine/v1beta1/package-info.java
  google-cloud-recommendations-ai/src/main/java/com/google/cloud/recommendationengine/v1beta1/stub/CatalogServiceStub.java
  google-cloud-recommendations-ai/src/main/java/com/google/cloud/recommendationengine/v1beta1/stub/CatalogServiceStubSettings.java
  google-cloud-recommendations-ai/src/main/java/com/google/cloud/recommendationengine/v1beta1/stub/GrpcCatalogServiceStub.java
  google-cloud-recommendations-ai/src/main/java/com/google/cloud/recommendationengine/v1beta1/stub/GrpcPredictionApiKeyRegistryStub.java
  google-cloud-recommendations-ai/src/main/java/com/google/cloud/recommendationengine/v1beta1/stub/PredictionApiKeyRegistryStub.java
  google-cloud-recommendations-ai/src/main/java/com/google/cloud/recommendationengine/v1beta1/stub/PredictionApiKeyRegistryStubSettings.java
  google-cloud-recommendations-ai/src/main/java/com/google/cloud/recommendationengine/v1beta1/stub/PredictionServiceStubSettings.java
  google-cloud-recommendations-ai/src/main/java/com/google/cloud/recommendationengine/v1beta1/stub/UserEventServiceStubSettings.java
  google-cloud-recommendations-ai/src/test/java/com/google/cloud/recommendationengine/v1beta1/CatalogServiceClientTest.java
  google-cloud-recommendations-ai/src/test/java/com/google/cloud/recommendationengine/v1beta1/PredictionApiKeyRegistryClientTest.java
  synth.metadata
Labels: automerge, cla: yes, context: full

#92 ci: switch to secret manager for sample/integration tests
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/integration.cfg
  .kokoro/presubmit/samples.cfg
  .kokoro/trampoline.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#93 samples: fix install for snippets
  README.md
  samples/snippets/pom.xml
  synth.metadata
Labels: cla: yes

#96 feat(deps): adopt flatten plugin and google-cloud-shared-dependencies
  .gitignore
  google-cloud-recommendations-ai/pom.xml
  grpc-google-cloud-recommendations-ai-v1beta1/pom.xml
  pom.xml
  proto-google-cloud-recommendations-ai-v1beta1/pom.xml
Labels: cla: yes

#98 fix: remove redundant properties from root pom
  pom.xml
Labels: cla: yes

#108 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none
