Repository googleapis/java-recommendations-ai, pull requests merged in 2021-05, with the labels that each got.

#313 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: recommendationengine, automerge, cla: yes, context: none

#314 chore: add enumeration data type to .repo-metadata.json
  .github/sync-repo-settings.yaml
  .repo-metadata.json
Labels: api: recommendationengine, automerge, cla: yes

#315 chore: add enumeration data type to .repo-metadata.json
  .repo-metadata.json
  sync-repo-settings.yaml
Labels: api: recommendationengine, automerge, cla: yes

#316 chore: Fix sync-repo-settings.yaml
  .github/sync-repo-settings.yaml
  synth.metadata
Labels: api: recommendationengine, automerge, cla: yes, context: none

#317 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: recommendationengine, cla: yes, context: full

#320 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: recommendationengine, automerge, cla: yes, context: full

#322 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: recommendationengine, automerge, cla: yes, context: full

#324 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: recommendationengine, automerge, cla: yes, context: full

#326 chore: dump maven version along with java
  .kokoro/build.sh
  synth.metadata
Labels: api: recommendationengine, automerge, cla: yes, context: full
