Repository googleapis/java-recommendations-ai, pull requests merged in 2021-09, with the labels that each got.

#403 chore: remove readme autosynth config
  .github/readme/synth.metadata/synth.metadata
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
Labels: automerge, kokoro:force-run, cla: yes, api: recommendationengine

#418 chore: change branch master to main in github configurations
  .github/sync-repo-settings.yaml
Labels: automerge, cla: yes, api: recommendationengine

#408 chore: relocate owl bot post processor
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
Labels: cla: yes, api: recommendationengine
